databaseChangeLog:
  - changeSet:
      id: 3e1b9f50-a7d0-4d97-8c78-fb8e6a2b6a88
      author: author(lubna)
      changes:
        - createTable:
            tableName: projects
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                    unique: true
                    primaryKeyName: project_id_pk
              - column:
                  name: name
                  type: VARCHAR(200)
                  constraints:
                    nullable: false
              - column:
                  name: type
                  type: VARCHAR(20)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: VARCHAR(20)
              - column:
                  name: start_date
                  type: DATE
                  constraints:
                    nullable: false
                    unique: true
              - column:
                  name: end_date
                  type: DATE
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  defaultValueComputed: CURRENT_TIMESTAMP
